### PR TITLE
Added options to remove coordinates from mini and world map

### PR DESCRIPTION
**Pull request by hatdragon**

### CODE REVIEW

**Review by nezroy — CHANGES_REQUESTED** [review]
I just updated changelog.txt/.lua to include placeholder for next release too. Please add changelog comment for this update to the NEW section of those (sign if you want)

**Comment by Nils89** [comment]
And you need to add the locals to every local file

**Comment by Nils89** [comment]
You can not rename or remove the local MINIMAP_COORDS this one is used in the HUD settings

**Comment by hatdragon** [comment]
I know.  I added it originally, but the text for it did not make sense after I added the ability to toggle the world map coordinates.

**Comment by Nils89** [comment]
You need to add a new one and reset the old one, otherwise the string does not match with the minimap hover option

**Comment by hatdragon** [comment]
Oh, I see, it's also used in the dropdown.   Okay.  Let me look a bit more into it.

**Comment by Nils89** [comment]
You could also use a drop down for that option. So there is only one setting. 
Drop down with the values:
Off
Minimap
Worldmap 
Both

**Comment by hatdragon** [comment]
Fixed the checkbox toggles and locales.   I can look into the dropdown if you think that would be a better solution overall?

**Pull request merged**
