### PR TITLE
Updated to Map Coordinates to support higher precision

### PR DESCRIPTION
**Pull request by hatdragon**
Added 2 decimal precision for coords.

### CODE REVIEW

**Comment by Nils89** [comment]
Maybe you can set this as a click option on click add 2 decimals, on click again zero?

**Comment by hatdragon** [comment]
> Maybe you can set this as a click option on click add 2 decimals, on click again zero?

I can take a look at that.  You just mean when clicking the coords from the minimap or should it be an option in the settings?

**Comment by Nils89** [comment]
I mean click on the coords is enough for this maybe with a tooltip for this like at the clock

**Comment by hatdragon** [comment]
Okay.   I'll take a stab at that in the morning then.

**Comment by hatdragon** [comment]
@Nils89 take a look when you have a chance, but that should take care of that.

**Pull request merged**
